# !/usr/bin/python3


# Creating a guesing game
import random


def get_random(a, s):
    """


    function to generate the random number
    :param a:
    the begining of the range
    :param s:
    the end of the range
    :return:


    it returns a random integer value
    """

    number = random.randint(a, s)
    return number


def factors(number):
    """


    function to get the factors ofthe given number
    :param number:


    number is used as the end number in the loop that checks numbers that are divisible by it
    :return:


    it returns the first five numbers that are divisible by the given number
    """

    empty = []

    for i in range(1, number + 1):

        if number % i == 0:

            empty.append(i)

    return f"The factors of  the number are: {empty[:-1]}"


print()


def divisible(number):
    """


    Function to check if the number is divisible by 2,3 and 5
    :param number:


    integer that is passed in as the random number and is checked wether its divisible by 2,3 and 5
    :return:


    returns string showing if its divisible or not
    """

    if number % 2 == 0:

        return "it is divisible by 2"

    elif number % 3 == 0:

        return "it is divisible by 3"

    elif number % 5 == 0:

        return "it is divisible by 5"

    elif number % 5 and number % 3 and number % 2:

        return "it is divisible by 2,3 and 5"
    else:

        return "its not divisible by 2,3,5"


def greater_or_smaller(number, value):
    """


    function to check if the given number is greater or equal to the given value
    :param number:


    the random number generated by the compputer


    :param value:


    this is given by the user to check if the number is greater or lower
    :return:


    it returns a string with the value showing if its greater or lower
    """

    if number > int(value):

        return f"Its greater than {value}"
    else:

        return f"Its less than {value}"


def main():

    marks = 100

    print("Welcome to the guessing game ")

    print("*" * 100)

    print(f"The max score is 100 points  \n for every wrong guess the 10 points are lost")

    print("*" * 100)

    print("choose the range of numbers you want either 1-10 or 10-100")

    print("*" * 100)

    a = int(input())

    s = int(input())

    random_number = get_random(a, s)

    print("A random number has been formed for you")

    print(random_number)

    while True:

        if marks != 0:

            print(" Enter your  guess ")
            print(" To Quit you can enter 'ex' and the game will stop")
            user_guess =input()
            if user_guess == 'ex':
                break
            elif int(user_guess) == random_number:

                print(
                    f"You got the random number {random_number} and got {marks} points")

                print("*" * 100)

                break

            else:

                funcs = [greater_or_smaller(random_number, int(user_guess)), factors(
                    random_number), divisible(random_number)]
                x = random.shuffle(funcs)

                marks -= 10

                print(f"Here's a hint for you {funcs[1]}")

                print("*" * 100)
        else:

            break


if __name__ == '__main__':
    main()
